urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'http://localhost:3000'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  name: 'example'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: false
    port: 4000
  cacheWarmer:
    enabled: false
    port: 5201
  transactionProcessor:
    enabled: false
    port: 5202
    maxLookBehind: 100
  queueWorker:
    enabled: false
    port: 8000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
